### ISSUE TITLE
Add install.sh script or equivalent

### ISSUE THREAD

**Issue by mjpitz** [indeedeng/go-groups#1]
Right now, I need to manually download the binary and move it into position. Can we provide a simple shell script that downloads the binary for the appropriate os/architecture that and places it in the users path?

**Comment by shoenig** [comment]
@mjpitz any go module with a `main` should be installable with just the `go get` command, and immediately executable if `$GOPATH/bin` is on your `$PATH`, e.g.

Is there something else you need?
```
[p1 ~] $ rm -rf ${GOPATH}/bin/*
[p1 ~] $ go get oss.indeed.com/go/go-groups
[p1 ~] $ go-groups -v
go-groups version 1.0.3 (2019-06-20)
```

**Comment by mjpitz** [comment]
interesting... I suspect that approach compiles the binary on the fly instead of leveraging the one built by ci/cd.

**Comment by shoenig** [comment]
Yeah, using only the `go` tool for Go builds is becoming more possible with modules. E.g. `goimports` recommends installing via `go get` 
https://godoc.org/golang.org/x/tools/cmd/goimports

For more complex builds, there's a pattern we're starting to use, [Tools as Dependencies](https://github.com/go-modules-by-example/index/tree/23a56e1095864bf596f2ce3aec296ecc89ab71b9/010_tools)
where we use `go:generate go run <module>` statements, with the module version encoded in the `go.mod` file of the the thing being built. The end result is reproducible builds using nothing more than the Go compiler.

**Comment by mjpitz** [comment]
Ok. Should we remove the binaries produced by the build process? Or keep them around?

**Comment by shoenig** [comment]
Anyone using `go-groups` is already going to have a Go environment configured, and should be able to just use `go-get`, making pre-built binaries probably not all that useful

**Comment by mjpitz** [comment]
I've removed the binary production and release plugin from the travis.yml file. Latest build passed: https://travis-ci.com/indeedeng/go-groups/builds/117072961
