### ISSUE TITLE
Support ignoring generated source files

### ISSUE THREAD

**Issue by ailurarctos** [indeedeng/go-groups#17]
Although most generated source files will produce `gofmt`-compliant code they will often produce Go source that does not adhere to the `go-groups` import style. It would be good if `go-groups` supported an option to detect and ignore generated source files based on the [documented](https://golang.org/pkg/cmd/go/internal/generate/) comment convention:

> ^// Code generated .* DO NOT EDIT\.$

**Comment by cnmcavoy** [comment]
This should be fixed in v1.1.1
