### ISSUE TITLE
Issues fetching binary over the last few days

### ISSUE THREAD

**Issue by mjpitz** [indeedeng/go-groups#20]
I've been having some rather sporadic build failures attributed to failures fetching to groups binary from Indeed:

```
unrecognized import path "oss.indeed.com/go/go-groups": reading https://oss.indeed.com/go/go-groups?go-get=1: 503 Service Unavailable
```

Here are two examples from today:
* https://github.com/depscloud/depscloud/runs/1221875124?check_suite_focus=true
* https://github.com/depscloud/depscloud/runs/1221875155?check_suite_focus=true

**Comment by mjpitz** [comment]
@cnmcavoy and @ailurarctos any thoughts?

**Comment by cnmcavoy** [comment]
@mjpitz I can confirm those requests appeared in our module proxy logs:
```
WARN 2020/10/07 12:32:53 [[mysql-driver] unexpected EOF]
WARN 2020/10/07 12:35:23 [[mysql-driver] unexpected EOF]
WARN 2020/10/07 12:36:53 [[mysql-driver] unexpected EOF]
```
I'll investigate how hard it is to make it do retries or cache better.

**Comment by cnmcavoy** [comment]
@mjpitz I made some changes to the Indeed Go proxy on the 9th. Have you seen any failed requests since then?

**Comment by mjpitz** [comment]
I haven't seen any recently and I haven't changed anything about my build process. I'll reach out again if I see anymore issues. Thanks! (ps, hope all is well!)
