### ISSUE TITLE
Getting 503s when installing go-groups

### ISSUE THREAD

**Issue by mjpitz** [indeedeng/go-groups#23]
This started happening again yesterday. Here's a recent failure: https://github.com/depscloud/depscloud/runs/1448351245?check_suite_focus=true

cc. @cnmcavoy

**Comment by cnmcavoy** [comment]
Confirmed. I will investigate adding a cache to these kinds of requests.

**Comment by mjpitz** [comment]
Is this modprox? Adding something like groupcache might be pretty easy to do.

**Comment by cnmcavoy** [comment]
It's not, but I set up a cache for the failing requests before thanksgiving. Are you still seeing spurious failures? The metrics I have show everything hitting the cache, so I'm hopeful that this is mitigated.

**Comment by mjpitz** [comment]
Haven't seen any since then... had some other fun errors with docker, but go-groups seems good.. Thanks for setting that up!
