### ISSUE TITLE
Use a real email address in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by indjb** [indeedeng/go-groups#4]
In [`CODE_OF_CONDUCT.md`](https://github.com/indeedeng/go-groups/blame/master/CODE_OF_CONDUCT.md#L58), there is no contact email listed, only

```
[INSERT EMAIL ADDRESS]
```

There should probably be a real email address.

**Comment by mjpitz** [comment]
@DuaneOBrien resolved this.
